### ISSUE TITLE
不是react全家桶的吗？没有router，redux

### ISSUE THREAD

**Issue by jinhuashijie** [YanYuanFE/react-start-app#2]
说明希望能够更详细一点，对于小白来说这些说明远远不够啊；而且启动速度有点过慢，大概需要五六分钟，难道是我电脑配置太低，i7+8G内存

**Comment by YanYuanFE** [comment]
最初我使用的是redux，是后来升级为dva，dva是蚂蚁金服开源的一款数据流管理框架，是redux的上层封装，包含了许多redux的最佳实践，router和ajax请求也包含在dva中，至于启动速度正在优化，但是npm start的时间不至于五六分钟吧，我的i7+8G， ubuntu系统是20秒左右。
