### ISSUE TITLE
打包后antd全部打包进入了vendor

### ISSUE THREAD

**Issue by myuanyuan** [YanYuanFE/react-start-app#3]
webpack4+redux+antd ，配置了按需加载，但是打包后vendor文件还是很大，600多k，请问你的是怎么处理的

**Comment by YanYuanFE** [comment]
entry: {
    app:[
        require.resolve('./polyfills'),
        paths.appIndexJs,require.resolve('react-error-overlay'),
        require.resolve('react-dev-utils/webpackHotDevClient')
    ],
    vendor: ['react', 'react-dom', 'react-router','react-router-dom', 'antd', 'echarts']
  },
使用了按需加载，antd不能放在vendor中。

**Comment by myuanyuan** [comment]
https://github.com/myuanyuan/pc-react-router-antd, this is the new respositor

**Comment by YanYuanFE** [comment]
你已经npm run eject释放webpack的配置了，就不用配置config-overrides了，直接配置babelrc，babelrc里面的[
            "@babel/preset-stage-2",
            {
                "loose": true,
                "decoratorsLegacy": true
            }
        ]这个删掉，不需要，会报错，没有安装

**Comment by YanYuanFE** [comment]
官方的这个配置太繁琐复杂了，你可以自己写一个简化版

**Comment by myuanyuan** [comment]
// 参照react-app-rewired方式写入config-overrides
const overrides = require('../config-overrides');
const webpackConfig = require('../config/webpack.config.prod');
require.cache[require.resolve('../config/webpack.config.prod')].exports =
  overrides(webpackConfig, process.env.NODE_ENV);
我在start和build里重写了react-app-rewired的代码，可以用config-overrides更改主题的，就剩下一个问题就是打包后文件太大，antd按需加载没起作用

**Comment by YanYuanFE** [comment]
config-overrides这个里面和babelrc里面都加了按需加载，重复了，去掉config-overrides试试，主题也可以不用这个配置，可以参考下我这个主题配置
