### ISSUE TITLE
有个问题。 我用jsx的语法写的时候， wepack 解析不了。但是我看你babel 中已经配置了 不知道为何 ，求解

### ISSUE THREAD

**Issue by shenjieming** [YanYuanFE/react-start-app#4]

**Comment by YanYuanFE** [comment]
可以贴一下代码吗?

**Comment by shenjieming** [comment]
没有。我用的也是 js 的文件。 方便的话可以 qq 联系下 我把代码贴给你

**Comment by shenjieming** [comment]
SyntaxError: D:\dev\demo\react-start-app\src\components\GetFormItem\getComponent.js: Unexpected token (72:21)

  70 |   const type = typeof compData
  71 |   if (type === 'string') {
> 72 |     const template = <span key={key}>{compData}</span>
     |                      ^
  73 |     return template
  74 |   } if (Array.isArray(compData)) {
  75 |     return compData.map((item, index) => getComponent(item, index))
    at Parser.raise (D:\dev\demo\react-start-app\node_modules\_@babel_parser@7.2.0@@babel\parser\lib\index.js:4028:15)

**Comment by shenjieming** [comment]
SyntaxError: D:\dev\demo\react-start-app\src\components\GetFormItem\getComponent.js: Unexpected token (72:21)

  70 |   const type = typeof compData
  71 |   if (type === 'string') {
> 72 |     const template = <span key={key}>{compData}</span>
     |                      ^
  73 |     return template
  74 |   } if (Array.isArray(compData)) {
  75 |     return compData.map((item, index) => getComponent(item, index))
    at Parser.raise (D:\dev\demo\react-start-app\node_modules\_@babel_parser@7.2.0@@babel\parser\lib\index.js:4028:15)

**Comment by shenjieming** [comment]
babel-loader 和demo 是一样的。 不知道为何 不支持 jsx 的语法

**Comment by shenjieming** [comment]
SyntaxError: D:\dev\demo\react-start-app\src\components\GetFormItem\getComponent.js: Unexpected token (72:21)

  70 |   const type = typeof compData
  71 |   if (type === 'string') {
> 72 |     const template = <span key={key}>{compData}</span>
     |                      ^
  73 |     return template
  74 |   } if (Array.isArray(compData)) {
  75 |     return compData.map((item, index) => getComponent(item, index))

**Comment by shenjieming** [comment]
ERROR in ./src/components/GetFormItem/getComponent.js
Module build failed (from ./node_modules/_babel-loader@8.0.4@babel-loader/lib/index.js):
SyntaxError: D:\dev\demo\react-start-app\src\components\GetFormItem\getComponent.js: Unexpected token (72:11)

  70 |   const type = typeof compData
  71 |   if (type === 'string') {
> 72 |     return <span key={key}>{compData}</span>
     |            ^
  73 |   } if (Array.isArray(compData)) {
  74 |     return compData.map((item, index) => getComponent(item, index))
  75 |   } if (type === 'object') {
