### ISSUE TITLE
Not working in IE11

### ISSUE THREAD

**Issue by jyotirmaybanerjee** [YanYuanFE/react-start-app#5]
I was trying in ie11 and got the below error. 

SCRIPT1010: Expected identifier
app.63bb3965601d79d2829f.js (6789,1)

And nothing renders.

**Comment by YanYuanFE** [comment]
Thanks, I has fix this issue,Sorry for the inconvenience! You can see this reason: https://github.com/facebook/prop-types/issues/254

**Comment by jyotirmaybanerjee** [comment]
Thanks for fixing it so quick.
