### ISSUE TITLE
调试

### ISSUE THREAD

**Issue by zhangmumu** [YanYuanFE/react-start-app#6]
本地调试如何可以不打包

**Comment by YanYuanFE** [comment]
本地调试npm start就可以，不会打包，打包是npm run build

**Comment by zhangmumu** [comment]
![image](https://user-images.githubusercontent.com/22143492/58868471-00309380-86ef-11e9-9282-23d7d25554e2.png)

**Comment by YanYuanFE** [comment]
这不是打包，这是在本地启动了一个devServer，happyPack 是用于提高webpack速度的插件，打包应该是把文件编译压缩输出到dist的过程。

**Comment by YanYuanFE** [comment]
npm start的编译文件操作在内存中进行，并没有输出到文件目录

**Comment by zhangmumu** [comment]
好的，了解了，谢谢了。
